# -*- coding: utf-8 -*-

"""
    foulefactoryapilib.models.payin_service_model
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
"""
from .base_model import BaseModel

class PayinServiceModel(BaseModel):

    """Implementation of the 'PayinServiceModel' model.

    TODO: type model description here.

    Attributes:
        amount (int): TODO: type description here.
        return_url (string): TODO: type description here.

    """

    def __init__(self, 
                 amount = None,
                 return_url = None):
        """Constructor for the PayinServiceModel class"""
        
        # Initialize members of the class
        self.amount = amount
        self.return_url = return_url

        # Create a mapping from Model property names to API property names
        self.names = {
            "amount" : "Amount",
            "return_url" : "ReturnUrl",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            amount = dictionary.get("Amount")
            return_url = dictionary.get("ReturnUrl")
            # Return an object of this model
            return cls(amount,
                       return_url)
