# -*- coding: utf-8 -*-

"""
    foulefactoryapilib.models.task_validation_writer_service_model
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
"""
from .base_model import BaseModel

class TaskValidationWriterServiceModel(BaseModel):

    """Implementation of the 'TaskValidationWriterServiceModel' model.

    TODO: type model description here.

    Attributes:
        id_task (int): TODO: type description here.
        state (string): TODO: type description here.

    """

    def __init__(self, 
                 id_task = None,
                 state = None):
        """Constructor for the TaskValidationWriterServiceModel class"""
        
        # Initialize members of the class
        self.id_task = id_task
        self.state = state

        # Create a mapping from Model property names to API property names
        self.names = {
            "id_task" : "IdTask",
            "state" : "State",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            id_task = dictionary.get("IdTask")
            state = dictionary.get("State")
            # Return an object of this model
            return cls(id_task,
                       state)
