# -*- coding: utf-8 -*-

"""
    foulefactoryapilib.models.template_instruction_writer_service_model
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
"""
from .base_model import BaseModel

class TemplateInstructionWriterServiceModel(BaseModel):

    """Implementation of the 'TemplateInstructionWriterServiceModel' model.

    TODO: type model description here.

    Attributes:
        instruction (string): TODO: type description here.
        order (int): TODO: type description here.

    """

    def __init__(self, 
                 instruction = None,
                 order = None):
        """Constructor for the TemplateInstructionWriterServiceModel class"""
        
        # Initialize members of the class
        self.instruction = instruction
        self.order = order

        # Create a mapping from Model property names to API property names
        self.names = {
            "instruction" : "Instruction",
            "order" : "Order",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            instruction = dictionary.get("Instruction")
            order = dictionary.get("Order")
            # Return an object of this model
            return cls(instruction,
                       order)
