# -*- coding: utf-8 -*-

"""
    foulefactoryapilib.models.template_column_writer_service_model
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/16/2016
"""
from .base_model import BaseModel

class TemplateColumnWriterServiceModel(BaseModel):

    """Implementation of the 'TemplateColumnWriterServiceModel' model.

    TODO: type model description here.

    Attributes:
        id_template_column_type (int): TODO: type description here.
        column (int): TODO: type description here.
        order (int): TODO: type description here.

    """

    def __init__(self, 
                 id_template_column_type = None,
                 column = None,
                 order = None):
        """Constructor for the TemplateColumnWriterServiceModel class"""
        
        # Initialize members of the class
        self.id_template_column_type = id_template_column_type
        self.column = column
        self.order = order

        # Create a mapping from Model property names to API property names
        self.names = {
            "id_template_column_type" : "IdTemplateColumnType",
            "column" : "Column",
            "order" : "Order",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            id_template_column_type = dictionary.get("IdTemplateColumnType")
            column = dictionary.get("Column")
            order = dictionary.get("Order")
            # Return an object of this model
            return cls(id_template_column_type,
                       column,
                       order)
